# Generated by Django 5.2.7 on 2025-11-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_bookshop_alter_customer_email_bookavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookavailability',
            name='edition',
            field=models.CharField(default='1st', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookavailability',
            unique_together={('book', 'edition', 'shop')},
        ),
    ]
