# Generated by Django 5.2.7 on 2025-11-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookavailability_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookavailability',
            name='edition',
            field=models.CharField(default='1st', max_length=50),
        ),
    ]
